open2c/cooltools

cooltools/cli/compute_saddle.py
solving https://github.com/mirnylab/cooltools/issues/12
`--vrange` is added in a least invasive way - without modifying `saddle.py`, using the fact that `digitize_track` function is dismissing  both `prange` and `by_percentile` as soon as provided `bins` is an array of some sort (not a single `int`).
All of that is made possible, because in the case of `vrange` we can generate bins without any prior knowledge of the track-values distribution (unlike `prange`).
Combining `vrange` and `by_percentile` is ultimately possible, but would require a priori "knowledge of the track-values distribution" - doesn't look nice with the current `saddle.py` API .
An effort was made to warn users about `--vrange` and to explain use cases. 
Testing was done, `vrange` seems to work as expected:
- using …
=> --vrange option added

cooltools/cli/compute_saddle.py
=> saddle cli import sys fix

setup.py
Adding scikit-learn as a new dependency required for the dot-caller
=> Update setup.py to add cikit-learn in dependencies

cooltools/cli/diamond_insulation.py, cooltools/insulation.py, setup.py
Updated develop branch with new insulation.py that loops over multiple window sizes.
=> Looping over window sizes in insulation score

cooltools/expected.py
just bringing all branches in line with `master`
=> Fixed imports in expected

cooltools/cli/call_dots.py
=> added balancing name flag to call_dots

cooltools/lib/numutils.py
Fix error introduced when migrating from mirnylib
=> Bugfix in zoom_array

cooltools/saddle.py
https://github.com/mirnylab/cooltools/issues/47
https://github.com/dekkerlab/Dekker-Lab-IT/issues/94
=> cooltools compute-saddle matplotlib bar API update

cooltools/lib/plotting.py
=> Migrate colormaps from mirnylib

cooltools/expected.py
=> Lists for multicolumn groupby

cooltools/cistot.py
with corrected main diagonal if it is not masked
=> cis and total calculation from coolers

README.md
Provide an example of how to use `call-compartments` to calculate eigenvectors.
=> Add call-compartments to README

cooltools/snipping.py
Snipper fixes: NaN filling of sparse matrix, chromosomes arms expected retrieval and ExpectedSnipper for different regions added.
=> Small snipper fixes

CHANGELOG.md, cooltools/cli/compute_saddle.py, cooltools/saddle.py, tests/test_compartments_saddle.py
As per our discussion: saved saddledata is not transformed while plotting is done with LogNorm.
=> Saddle scale

cooltools/__init__.py, cooltools/eigdecomp.py, requirements.txt
re: https://github.com/mirnylab/bioframe/issues/27
=> Synchronize cooltools 0.3 with bioframe 0.0

cooltools/cli/genome.py
move help from click argument to the fuction doc-string - to fix cooltools cli
quick fix  - for https://github.com/mirnylab/cooltools/commit/1dbdd3dbf01ef7e1180544ef531dd30c97b3a5b4#commitcomment-39538718
=> undo help inside click-argument

cooltools/snipping.py
A bugfix addressing issue https://github.com/mirnylab/cooltools/issues/168
@agalitsyna  - does this seem right?
=> snipping now selects correct regions from expected

cooltools/cli/compute_saddle.py, requirements.txt, tests/data/mm9.named_nonoverlap_regions.bed, tests/data/mm9.named_overlap_regions.bed, tests/test_expected.py
keep cleaning after the expected update ...
now just resolved the compatibility between current output of cli expected and whatever compute-saddle wants it to be (added `--regions` option to saddle, but it's not 100% functional yet)
also added a simple cli compute-expected test...
tests should pass now
=> add expected test, make saddle tests pass

cooltools/cli/diamond_insulation.py
Addresses https://github.com/mirnylab/cooltools/issues/175
I didn't touch the `genome` tools though, should I?
=> Allow --output in diamond-insulation

cooltools/expected.py
Removed non-interpretable columns from output, updated documentation and supplemental gist.
=> Minor changes to logbin-expected

cooltools/cli/diamond_insulation.py
Resolving https://github.com/open2c/cooltools/issues/256
related to : 
https://github.com/open2c/cooltools/issues/291
=> enhancement(diamond_insualtion): --bigwig output.

cooltools/cli/call_dots.py, cooltools/cli/logbin_expected.py, cooltools/expected.py, cooltools/lib/common.py, cooltools/lib/schemas.py, tests/data/CN.mm9.toy_expected.chromnamed.tsv, tests/data/CN.mm9.toy_expected.tsv, tests/test_expected.py
fixing issues assigned to @sergpolly , miscelaneous cleanup
=> WIP small fixes to expected and such

cooltools/api/coverage.py, cooltools/cli/__init__.py, cooltools/cli/coverage.py
I realized there was no CLI for coverage, so I created one
=> Add CLI tool for coverage

cooltools/api/insulation.py, cooltools/cli/insulation.py
Insulation API and CLI was not parallel for some reason. I made it parallel and it seems to speed up computations. 
Here is an example from open2c_examples insulation notebook: 
One thing that I do not understand completely is behavior of CSRSelector in multithreading mode. I had to create multiple instances of selectors for each thread. Are multiple CSRSelectors  guaranteed to work in order on a single cooler in multithreading? @nvictus
=> Multithread insulation

cooltools/api/snipping.py, tests/test_snipping.py
Start docs for low-level snipping by creating docstrings for snippers
=> Docstrings for snippers

cooltools/api/snipping.py, tests/test_snipping.py
whaaat I didn't merge this how did it happen aaaa
=> Revert "Docstrings for snippers"

cooltools/lib/checks.py
Fix https://github.com/open2c/cooltools/issues/411
=> Fix warn in checks

requirements.txt
addresses #435 and #433  - temporary installation fix to get tests going - need actual changes to make it compatible with the new bioframe and pandas
=> temporary fix for tests: pandas<2, bioframe<0.4

requirements.txt
=> Pin bioframe >=0.4.1

cooltools/sandbox/cross_score.py
- Naming issues and CLI fix of cross-score
- Black 
- Fixing an edge case for bin-wise annotation of cross-scores
=> Cross score sandbox fixes
