- cooltools/eigdecomp.py
Set default ordering of EVs to sorting by eigenvalue (sort_by_gc_corr=False) in cis eigenvalue decompositions and added recommendation accordingly
> Turn off default gc ordering of EVs in cis

- cooltools/expected.py
`trans_expected` updated to return a table of interactions/bins for each  inter-chromosomal pair.
The only problem is `use_dask=True` would lead to failure, as of right now, because of the `dask` issues:
https://github.com/dask/dask/issues/811
https://github.com/dask/dask/issues/772
> trans_expected update by @nvictus

- cooltools/cli/__init__.py
- cooltools/cli/compute_expected.py
- cooltools/cli/expected.py
- cooltools/expected.py
Simple CLI wrapper for expected.py:
```
cooltools compute_expected --cis in.cool
cooltools compute_expected --trans in.cool
```
Using bunch of cores:
```
cooltools compute_expected -n 8 --cis in.cool
cooltools compute_expected -n 8 --trans in.cool (would raise NotImplemented)
```
NOTES:
Wrapper works fine with the latest `dask`(0.17.0) and `distributed`(1.21.0).
Only `stdout` output is implemented, just like for `diamond_insulation`.
TODO:
- Should probably add `ignore_diags` as a `click` option - will do later.
- Improve my usage of `click` options - i provided links to `click` features I tried to use, but `help` looks ugly a bit.
- do we have to explicitly shutdown `distributed`  cluster ?
> cli wrapper for expected

- cooltools/cli/__init__.py
- cooltools/cli/compute_saddle.py
- cooltools/saddle.py
saddle cli conversation starter ...
There are too many things going on at the same time, for me alone to decide everything.
- I tried my best to add some cross-validation to make sure cooler, track and expected are compatible between each other.
- took the actual working part from Nezar's and Ankita's implementations https://github.com/nandankita/labUtilityTools
- did some effort to produce sensible text-outputs - needs to be finalized a bit
- savefig to generate an actual saddleplot. no interactive plots for now
- already using chrom-chrom pairs trans expected, not quite ready for chromosomes-arms (is that even a thing?) ...
- fetcher/getter functions updated accordingly, sometimes switching from `groupby` to using pandas indexing
TODO:
- update help (it's a mess now)
- improve output …
> Saddle cli

- cooltools/cli/call_dots.py
addressing https://github.com/mirnylab/cooltools/issues/27
just a variables scope bug, that is activated only with `verbose` output
> w,p variables scope fix

- cooltools/eigdecomp.py
master keeps running ahead ...
> eigdecomp.py: remove a leading slash in load_attrs [ignore_diags]

- cooltools/insulation.py
- cooltools/lib/_query.py
This PR adds a private `lib._query` that allows taking large delayed range queries and materializing them in smaller pieces, to reduce memory constraints: e.g. selecting a whole chromosome for computing insulation score at very high resolutions. We can begin using it in different cooltools and adjust the API until we are happy with it, at which point it can be migrated into cooler. This PR updates insulation score to use the new machinery.
ping @sergpolly in case this might be useful for dots
> Granular query machinery for diamond insulation

- environment.yml
- requirements-dev.txt
- requirements.txt
- setup.py
* Add requirements and requirements-dev files. To be kept loosely pinned.
* Add matplotlib to requirements
* Parse `install_requires` from requirements.txt
> Parse setup dependencies from requirements file

- cooltools/cli/compute_saddle.py
- cooltools/saddle.py
Allow `--min-dist` and `--max-dist` arguments for `compute-saddle`.
Addresses https://github.com/mirnylab/cooltools/issues/54
Here is an example with some mouse ES cell data with mindist from 0 to 48 in 12 Mb increments, for 12 Mb bands (like in the Abramo paper).
> Saddle distance

- cooltools/lib/numutils.py
Somehow default zoom order was set to 3 instead of a much better default of 1! Goes against the docstring too.
> Set default zoom order to 1

- cooltools/snipping.py
fixes error for np.nan & int clash that emerges w/ balancecooltools.snipping.CoolerSnipper(clr, cooler_opts={'balance':False})
lmk if there's a more elegant fix.
> snipping-fix-for-balance-opts

- cooltools/eigdecomp.py
- cooltools/saddle.py
- tests/test_compartments_saddle.py
saddles were broken for `--contact-type trans` - and this PR is a quick fix for that
also added a couple of trans related tests - compartment and saddle CLI , in order to make sure trans-business isn't neglected going forward - WE NEED MOAR TESTS !
also updated some docstrings -because it took me awhile to understand what's written in there ... and some vriable names as well for the same reason - less confusion , better maintenance !
> fix trans saddles a bit, add trans tests

- cooltools/eigdecomp.py
- cooltools/lib/_numutils.pyx
Missing break statement caused `fake_cis` to only sample from the same row, but not the same column.
Also changed the mask dtype to `uint8` to conserve space.
> Fix fake_cis sampling bug

- cooltools/eigdecomp.py
- cooltools/lib/numutils.py
replacing https://github.com/open2c/cooltools/pull/204 - because of the `develop`-branch mess
- updates `cool_cis_eig` - docstring, comments, allow input `regions` as `DataFrame`, allow multiprocess `map`, `bad_regions`, etc
- update `numutils.get_eig` - prevent an edge case, when # of requested eigens > `mat_collapsed` size (e.g. small arm) which used to make it crash with "index of out bound" - now it'll just backfill eigens with `NaNs`
> cools_cis_eig work with regions as DF, numutils eig update

- cooltools/snipping.py
- tests/test_snipping.py
Related to https://github.com/open2c/cooltools/commit/1a637919bc8c1f2bee31a605491fb7d75fb65221
which turned out to be not a complete fix.
> bugfix(snipping): features with empty regions return snips filled with NaNs

- cooltools/cli/call_compartments.py
- cooltools/cli/call_dots.py
- cooltools/cli/compute_expected.py
- cooltools/cli/compute_saddle.py
- cooltools/dotfinder.py
- cooltools/eigdecomp.py
- cooltools/expected.py
- cooltools/saddle.py
- cooltools/snipping.py
- tests/test_expected.py
- tests/test_snipping.py
I left the old names in places where we need to fix the code anyway, e.g. asym expected
> Rename regions to view everywhere

- README.md
- cooltools/cli/compute_saddle.py
- cooltools/cli/logbin_expected.py
- cooltools/saddle.py
- requirements.txt
- tests/test_compartments_saddle.py
updates & refactoring & tests for `cooltools.saddle` with https://github.com/open2c/cooltools/issues/258 in mind. 
- `get_saddle()` replaces `make_saddle`, and directly accepts (clr, expected, digitized_track), which will clarify the API.
- obs/expected fetchers are now underscored and understood as helper functions for `get_saddle`.
- `get_digitized` returns a dataframe and binedges instead of a histogram, and merges in what had previously been used in the CLI for bin creation. 
- digitized track is now a **categorical**
in the end, I decided that two separate functions for cis vs trans wasn't 100% necessary, and that it wouldn't be overly cumbersome to have the digitized track as a requirement for get_saddle, since it now contains the bin information in its categories.
> Saddle refactor

- cooltools/api/eigdecomp.py
- cooltools/sandbox/expected_smoothing.py
- tests/test_expected.py
changing the default behavior of bioframe.make_viewframe to not create UCSC names made the following code incompatible:
```python
common_regions = []
for i in range(4):
chrom = chromosomes[i]
halfway_chrom = int(chromsizes[chrom] / 2)
halfway_chrom = round(halfway_chrom / assumed_binsize) * assumed_binsize
reg1 = (chrom, 0, halfway_chrom)
reg2 = (chrom, halfway_chrom, chromsizes[chrom])
common_regions.append(reg1)
common_regions.append(reg2)
view_df = bioframe.make_viewframe(common_regions)
```
fixed by passing `name_style="ucsc"`
> fix-test_expected-after-bioframe-make_viewframe-name_style-update

- cooltools/api/insulation.py
- tests/test_insulation.py
addresses #369 
also deleted duplicated input validation from `insulation` for window_bp, as that is handled by  `calculate_insulation_score`
> cast-to-int-for-insulation-window_bp

- cooltools/__init__.py
- cooltools/api/virtual4c.py
- cooltools/cli/__init__.py
- cooltools/cli/virtual4c.py
- docs/cooltools.rst
- tests/test_virtual4c.py
API and CLI for virtual 4C.
No support for expected (for now?).
> Create virtual 4C tool

- cooltools/lib/io.py
- tests/test_checks.py
- tests/test_io.py
Addresses issues:
https://github.com/open2c/cooltools/issues/384
https://github.com/open2c/cooltools/issues/334
read_expected_from_file takes dtypes from schemas which avoids certain errors when not setting dtypes. Added test to throw error if dtype is incompatible (str->int).
Any comments welcome
> read_expected_from_file set dtypes

- .gitignore
- datasets/external_test_files.tsv
Added an mcooler with chr2 and chr17 for hESCs, it's uploaded to OSF and should be available with standard cooltools test data download functions.
> Added test data for hESCs

- pyproject.toml
Adds a `pyproject.toml`, specifying a `build-system` that includes dependencies required to run `setup.py` (`Cython` & `numpy`).
Ran into a situation like #138 a couple of times installing `cooltools` in a fresh environment. This should prevent these errors. 
You can test in a clean environment:
```sh
conda create --name cooltools python=3.10
conda activate cooltools
pip install -e .
```
> chore: add pyproject.toml

- cooltools/api/dotfinder.py
- tests/test_dotfinder_stats.py
small fixes in dotfinder to prevent IndexErrors in `extract_scored_pixels`: prevent `NaN`- valued pixel scores, consider "non-monotonous" histogram
> Dotsfix to prevent more IndexErrors

- cooltools/lib/io.py
- tests/test_io.py
engaged `schema_is_strict=True` for reading `bed4` or `bed3` viewframe from file addressing #421
I checked and it ooks like this is the only place where we use `bioframe.read_table` so this should be ok from generality perspective
> fix 421 - allow view without names

- .gitignore
- cooltools/api/snipping.py
- tests/test_snipping.py
Fixes https://github.com/open2c/cooltools/issues/406
And addresses comments from https://github.com/open2c/cooltools/pull/418, and supersedes it.
(except the idea for a test for correct symmetrization... but np.fmax seems foolproof!)
> Symmetrize on-diagonal pileups correctly

- cooltools/lib/numutils.py
See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit
> nopython=True due to deprecation warning

- cooltools/lib/numutils.py
The adaptive_coarsegrain function doesn't work when using NumPy 1.24 and later because line [1318](https://github.com/open2c/cooltools/blob/8af2b1087f7302d282dc77a82047ac0a3a8339c1/cooltools/lib/numutils.py#L1318C1-L1319C1) in cooltools/cooltools/lib/numutils.py uses `np.int`, which was deprecated in NumPy 1.20 and fully removed in NumPy 1.24 (see [here](https://numpy.org/devdocs/release/1.20.0-notes.html)). It should be replaced by `int` or `np.int_`. 
Per the suggestion from @nvictus in issue [472](https://github.com/open2c/cooltools/issues/472), I opted for the `int` option.
> Replaced np.int with int in adaptive_coarsegrain

- CHANGELOG.md
- cooltools/__init__.py
> update version and changelog

- cooltools/lib/plotting.py
> an attempt to fix register_cmap import in plotting

- cooltools/lib/plotting.py
fixing a bug introduced in #533
> make register_cmap backward compatible wrt to argument order
